import { useMemo, useState } from "react";

import {
  CalendarDays,
  Clock,
  MapPin,
  Sparkles,
  Train,
  Zap,
  Wrench,
  Radio,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

import { maintenanceTasks } from "../data/maintenanceData";
import { generateBlockPlan } from "../utils/blockPlanner";

function BlockPlanning() {
  const [expandedBlock, setExpandedBlock] = useState(null);

  const blockPlans = useMemo(() => {
    return generateBlockPlan(maintenanceTasks);
  }, []);

  const totalDowntimeSaved = blockPlans.reduce(
    (total, block) =>
      total + block.downtimeSaved,
    0
  );

  const totalTasks = blockPlans.reduce(
    (total, block) =>
      total + block.taskCount,
    0
  );

  const getDepartmentIcon = (department) => {
    if (department === "Engineering") {
      return <Wrench size={15} />;
    }

    if (
      department ===
      "Signal & Telecommunication"
    ) {
      return <Radio size={15} />;
    }

    return <Zap size={15} />;
  };

  return (
    <div className="block-planning-page">

      <div className="page-heading block-heading">
        <div>
          <p className="welcome-label">
            AI-POWERED OPTIMIZATION ENGINE
          </p>

          <h1>Automatic Block Planning</h1>

          <p>
            Coordinated maintenance blocks generated by
            analyzing task priority, corridor location,
            departments, and maintenance duration.
          </p>
        </div>

        <button className="generate-button">
          <Sparkles size={18} />
          Regenerate AI Plan
        </button>
      </div>

      {/* SUMMARY CARDS */}

      <div className="block-summary-grid">

        <div className="block-summary-card">
          <div className="summary-icon blue">
            <CalendarDays size={22} />
          </div>

          <div>
            <span>Optimized Blocks</span>
            <h2>{blockPlans.length}</h2>
          </div>
        </div>

        <div className="block-summary-card">
          <div className="summary-icon green">
            <Clock size={22} />
          </div>

          <div>
            <span>Downtime Saved</span>
            <h2>{totalDowntimeSaved.toFixed(1)} hrs</h2>
          </div>
        </div>

        <div className="block-summary-card">
          <div className="summary-icon orange">
            <Wrench size={22} />
          </div>

          <div>
            <span>Tasks Coordinated</span>
            <h2>{totalTasks}</h2>
          </div>
        </div>

        <div className="block-summary-card">
          <div className="summary-icon purple">
            <Sparkles size={22} />
          </div>

          <div>
            <span>AI Confidence</span>
            <h2>
              {Math.round(
                blockPlans.reduce(
                  (total, block) =>
                    total + block.aiConfidence,
                  0
                ) / blockPlans.length
              )}
              %
            </h2>
          </div>
        </div>

      </div>

      {/* BLOCK PLANS */}

      <section className="block-plan-section">

        <div className="section-title">
          <div>
            <h2>AI Generated Block Schedule</h2>
            <p>
              Tasks are grouped to minimize railway
              infrastructure downtime.
            </p>
          </div>

          <span className="live-status">
            <span></span>
            AI PLAN READY
          </span>
        </div>

        <div className="block-list">

          {blockPlans.map((block) => {
            const isExpanded =
              expandedBlock === block.id;

            return (
              <div
                className="block-card"
                key={block.id}
              >

                <div className="block-card-main">

                  <div className="block-corridor">
                    <div className="corridor-icon">
                      <Train size={24} />
                    </div>

                    <div>
                      <span className="block-id">
                        {block.id}
                      </span>

                      <h3>{block.corridor}</h3>

                      <span
                        className={`priority ${block.highestPriority.toLowerCase()}`}
                      >
                        {block.highestPriority} Priority
                      </span>
                    </div>
                  </div>

                  <div className="block-info">

                    <div>
                      <CalendarDays size={17} />
                      <span>{block.blockDate}</span>
                    </div>

                    <div>
                      <Clock size={17} />
                      <span>{block.timeSlot}</span>
                    </div>

                    <div>
                      <MapPin size={17} />
                      <span>
                        {block.taskCount} Tasks
                      </span>
                    </div>

                  </div>

                  <div className="block-saving">
                    <span>Downtime Saved</span>
                    <strong>
                      {block.downtimeSaved.toFixed(1)} hrs
                    </strong>
                  </div>

                  <button
                    className="expand-button"
                    onClick={() =>
                      setExpandedBlock(
                        isExpanded
                          ? null
                          : block.id
                      )
                    }
                  >
                    {isExpanded ? (
                      <ChevronUp size={20} />
                    ) : (
                      <ChevronDown size={20} />
                    )}
                  </button>

                </div>

                {isExpanded && (

                  <div className="block-details">

                    <div className="block-details-grid">

                      <div className="planned-tasks">
                        <h4>
                          Maintenance Activities
                        </h4>

                        {block.tasks.map((task) => (
                          <div
                            className="planned-task"
                            key={task.id}
                          >
                            <div className="task-department-icon">
                              {getDepartmentIcon(
                                task.department
                              )}
                            </div>

                            <div>
                              <strong>
                                {task.task}
                              </strong>

                              <span>
                                {task.department} •{" "}
                                {task.location} •{" "}
                                {
                                  task.estimatedHours
                                }{" "}
                                hrs
                              </span>
                            </div>

                            <span
                              className={`priority ${task.priority.toLowerCase()}`}
                            >
                              {task.priority}
                            </span>
                          </div>
                        ))}
                      </div>

                      <div className="optimization-result">

                        <h4>
                          AI Optimization Result
                        </h4>

                        <div className="optimization-row">
                          <span>
                            Separate Blocks
                          </span>

                          <strong>
                            {block.separateBlockHours.toFixed(
                              1
                            )}{" "}
                            hrs
                          </strong>
                        </div>

                        <div className="optimization-row">
                          <span>
                            Coordinated Block
                          </span>

                          <strong>
                            {block.blockDuration.toFixed(
                              1
                            )}{" "}
                            hrs
                          </strong>
                        </div>

                        <div className="optimization-row saved">
                          <span>
                            Time Saved
                          </span>

                          <strong>
                            {block.downtimeSaved.toFixed(
                              1
                            )}{" "}
                            hrs
                          </strong>
                        </div>

                        <div className="confidence-box">
                          <Sparkles size={17} />

                          <div>
                            <span>
                              AI Confidence
                            </span>

                            <strong>
                              {
                                block.aiConfidence
                              }
                              %
                            </strong>
                          </div>
                        </div>

                      </div>

                    </div>

                    <div className="department-section">

                      <span>
                        Coordinated Departments
                      </span>

                      <div className="department-tags">

                        {block.departments.map(
                          (department) => (
                            <div
                              className="department-tag"
                              key={department}
                            >
                              {getDepartmentIcon(
                                department
                              )}

                              {department}
                            </div>
                          )
                        )}

                      </div>

                    </div>

                  </div>
                )}

              </div>
            );
          })}

        </div>

      </section>

    </div>
  );
}

export default BlockPlanning;